### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setdefault'

### ISSUE THREAD

**Issue by paulocheque** [soasme/beeper.py#12]
Maybe it could have a "beeper.yml" validation to show more clear messages like "missing required parameter in beeper.yml file"

```
Traceback (most recent call last):
  File "/usr/local/bin/beeper", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/beeper/cmd.py", line 61, in build
    conf = _read_conf(conf, version, format)
  File "/Library/Python/2.7/site-packages/beeper/cmd.py", line 43, in _read_conf
    conf.setdefault('language', 'python')
AttributeError: 'NoneType' object has no attribute 'setdefault'
```

**Comment by soasme** [comment]
Thanks. This bug will be fixed in next release.

**Comment by soasme** [comment]
Bug fixed. Version 0.9.2
